---
title: "palma_ids"
output: html_document
---

#NOSIA-II
```{r}
library(httr)
library(rlist)
library(dplyr)
library(reactable)
library(devtools)
library(jsonlite)
library(tidyverse)
library(flextable)
library(officer)
library(writexl)
#install_github("jeroenooms/jsonlite")
#eores<-"https://eorestest.nesdis-hq.noaa.gov/ws/ws/"
#eores<-https://eoreswstest2.nesdis-hq.noaa.gov/ws/ws/"
#eores<-"https://eores.nesdis-hq.noaa.gov/ws/ws/"
eores<-"https://eores.nesdis-hq.noaa.gov/ws/ws/"

#treename<-"EOA2016"
treename<-"NOSIA-II"
#treename<-"NOSIA-2-1"
```

```{r}
#networks
r<-GET(paste0(eores,"get_reports_network_basic_information",sep=""))
json_text<-content(r, as = "text")
networks_json<-fromJSON(json_text)
networks<-networks_json[['rptntwrkbasic']]

#networks palma
r<-GET(paste0(eores,"get_reports_network_palma_id",sep=""))
json_text<-content(r, as = "text")
networks_palma_json<-fromJSON(json_text)
networks_palma<-networks_palma_json[['rptntwrkpalmaid']]

#networks2systems
r<-GET(paste0(eores,"get_reports_network_observing_system_associations",sep=""))
json_text<-content(r, as = "text")
networks2systems_json<-fromJSON(json_text)
networks2systems<-networks2systems_json[['rptntwrk2system']]

#systems
r<-GET(paste0(eores,"get_reports_observing_system_basic_information",sep=""))
json_text<-content(r, as = "text")
systems_json<-fromJSON(json_text)
systems<-systems_json[['rptsystembasic']]

#systems palma
r<-GET(paste0(eores,"get_reports_observing_system_palma_id",sep=""))
json_text<-content(r, as = "text")
systems_palma_json<-fromJSON(json_text)
systems_palma<-systems_palma_json[['rptsystempalmaid']]

#platforms
r<-GET(paste0(eores,"get_reports_platform_basic_information",sep=""))
json_text<-content(r, as = "text")
platforms_json<-fromJSON(json_text)
platforms<-platforms_json[['rptpltfrmbasic']]

#platform palma
r<-GET(paste0(eores,"get_reports_platform_palma_id",sep=""))
json_text<-content(r, as = "text")
platforms_palma_json<-fromJSON(json_text)
platforms_palma<-platforms_palma_json[['rptpltfrmpalmaid']]

#platforms2system
r<-GET(paste0(eores,"get_reports_observing_system_platform_associations",sep=""))
json_text<-content(r, as = "text")
platform2system_json<-fromJSON(json_text)
platform2system<-platform2system_json[['rptsystem2pltfrm']]

#Sensing Elements
r<-GET(paste0(eores,"get_reports_sensing_element_basic_information",sep=""))
json_text<-content(r, as = "text")
se_json<-fromJSON(json_text)
se<-se_json[['rptsebasic']]

#Sensing Elements palma
r<-GET(paste0(eores,"get_reports_sensing_element_palma_id",sep=""))
json_text<-content(r, as = "text")
se_palma_json<-fromJSON(json_text)
se_palma<-se_palma_json[['rptsepalmaid']]

#se2platform
r<-GET(paste0(eores,"get_reports_platform_sensing_element_associations",sep=""))
json_text<-content(r, as = "text")
se2platform_json<-fromJSON(json_text)
se2platform<-se2platform_json[['rptpltfrm2se']]

#environmental parameters
r<-GET(paste0(eores,"get_reports_environmental_parameter_basic_information",sep=""))
json_text<-content(r, as = "text")
ep_json<-fromJSON(json_text)
ep<-ep_json[['rptenvparambasic']]

#environmental parameters palma
r<-GET(paste0(eores,"get_reports_environmental_parameter_palma_id",sep=""))
json_text<-content(r, as = "text")
ep_palma_json<-fromJSON(json_text)
ep_palma<-ep_palma_json[['rptenvparampalmaid']]

#se2ep
r<-GET(paste0(eores,"get_reports_sensing_element_environmental_parameter_associations",sep=""))
json_text<-content(r, as = "text")
ep2se_json<-fromJSON(json_text)
ep2se<-ep2se_json[['rptse2envparam']]

#data sources
r<-GET(paste0(eores,"get_reports_data_sources",sep=""))
json_text<-content(r, as = "text")
datasrc_json<-fromJSON(json_text)
datasrc<-datasrc_json[['rptdatasrc']]
```

```{r}
system_joins <- networks_palma %>%
  left_join(networks, by = "network_id") %>% 
  select(network_id:network_acronym) %>% 
  left_join(networks2systems, by = "network_id") %>% 
  select(-network_id, -network_system_id) %>% 
  dplyr::rename(networks_palma_id = palma_id) %>%
  full_join(systems, by = "system_id")%>%
#  filter(osc_baseline_observing_system_category== "Critical") %>%
  select(network_name, network_acronym, networks_palma_id, system_id, system_name, system_acronym, system_life_cycle_phase, system_type) %>%
  left_join(systems_palma, by = "system_id") %>%
  left_join(platform2system, by = "system_id") %>% 
  select(-system_id, -system_palma_id_id, -system_platform_id) %>%
  left_join(platforms, by = "platform_id") %>% 
  select(network_name:platform_acronym, platform_life_cycle_phase) %>% 
  dplyr::rename(systems_palma_id = palma_id) %>% 
  left_join(platforms_palma, by = "platform_id") %>%
  left_join(se2platform, by = "platform_id") %>%
  select(-platform_id, -platform_palma_id_id, -platform_sensing_element_id) %>%
  dplyr::rename(platforms_palma_id = palma_id) %>%
  left_join(se, by = "sensing_element_id") %>% 
  select(network_name:sensing_element_acronym, sensing_element_life_cycle_phase) %>% 
  left_join(se_palma, by = "sensing_element_id") %>% 
  dplyr::rename(se_palma_id = palma_id) %>%
  left_join(ep2se, by = "sensing_element_id") %>% 
  select(-sensing_element_palma_id_id, -sensing_element_environmental_parameter_id) %>% 
  left_join(ep, by = "environmental_parameter_id") %>% 
  select(network_name:environmental_parameter_name) %>% 
  left_join(ep_palma, by = "environmental_parameter_id") %>% 
  select(-environmental_parameter_id, -environmental_parameter_palma_id_id, -sensing_element_id) %>%
  dplyr::rename(ep_palma_id = palma_id) %>%
  mutate(acro_palma_all = paste(network_acronym, networks_palma_id, system_acronym, systems_palma_id, platform_acronym, platforms_palma_id, sensing_element_acronym, se_palma_id, ep_palma_id, sep = ";")) %>%
  distinct(acro_palma_all, .keep_all = TRUE)
```

Investigation into palma ids at multiple levels
```{r}
df<- system_joins %>%
  select(-system_life_cycle_phase, -system_type, -platform_life_cycle_phase, -sensing_element_life_cycle_phase) %>%
  mutate(networks_palma_id = as.factor(ifelse(is.na(networks_palma_id), "n.", paste0(networks_palma_id,"$")))) %>%
  mutate(systems_palma_id = as.factor(ifelse(is.na(systems_palma_id), "s.", paste0(systems_palma_id,"$")))) %>%
  mutate(platforms_palma_id = as.factor(ifelse(is.na(platforms_palma_id), "p.", paste0(platforms_palma_id,"$")))) %>%
  mutate(se_palma_id = as.factor(ifelse(is.na(se_palma_id), "x.", paste0(se_palma_id, "$")))) %>%
  mutate(ep_palma_id = as.factor(ifelse(is.na(ep_palma_id), "y.", paste0(ep_palma_id, "$")))) %>%
  select(networks_palma_id,systems_palma_id, platforms_palma_id, se_palma_id, ep_palma_id) %>%
  mutate(network_multiple = ifelse(networks_palma_id %in% c(systems_palma_id, platforms_palma_id, se_palma_id, ep_palma_id), 1, 0)) %>%
  mutate(system_multiple = ifelse(systems_palma_id %in% c(networks_palma_id, platforms_palma_id, se_palma_id, ep_palma_id), 1, 0)) %>%
  mutate(platform_multiple = ifelse(platforms_palma_id %in% c(networks_palma_id, systems_palma_id, se_palma_id, ep_palma_id), 1, 0)) %>%
  mutate(se_multiple = ifelse(se_palma_id %in% c(networks_palma_id, systems_palma_id, platforms_palma_id, ep_palma_id), 1, 0)) %>%
  rowwise() %>%
  mutate(multiple = sum(c_across(network_multiple:se_multiple))) %>% View()
  
df$multiple_network <- rowSums(sapply(df[2:5], grepl, pattern = df$networks_palma_id, fixed = TRUE))
df$multiple_system <-rowSums(sapply(df[c(1,3,4,5)], grepl, pattern = df$systems_palma_id, fixed = TRUE))
df$multiple_platform<-rowSums(sapply(df[c(1,2,4,5)], grepl, pattern = df$platforms_palma_id, fixed = TRUE))
df$multiple_se<-rowSums(sapply(df[c(1,2,3,5)], grepl, pattern = df$se_palma_id, fixed = TRUE))
df$multiple_ep<-rowSums(sapply(df[c(1,2,3,4)], grepl, pattern = df$ep_palma_id, fixed = TRUE))
df$multiple<- rowSums(df[6:10])
  
  mutate(acro_palma_all = paste(networks_palma_id,systems_palma_id, platforms_palma_id, se_palma_id, ep_palma_id, sep = ";")) %>% 


#  filter(duplicated(cbind(networks_palma_id, systems_palma_id, platforms_palma_id, se_palma_id, ep_palma_id))) %>%

```




```{r cars}
ntwk<- system_joins %>%
  select(networks_palma_id) %>%
  distinct(networks_palma_id) %>%
  mutate(eos_palma_level = "network") %>% rename(palma_id = networks_palma_id)

sys<- system_joins %>%
  select(systems_palma_id) %>%
  distinct(systems_palma_id) %>%
  mutate(eos_palma_level = "system") %>% rename(palma_id = systems_palma_id)

plat<- system_joins %>%
  select(platforms_palma_id) %>%
  distinct(platforms_palma_id) %>%
  mutate(eos_palma_level = "platform") %>% rename(palma_id = platforms_palma_id)

sensing_element<- system_joins %>%
  select(se_palma_id) %>%
  distinct(se_palma_id) %>%
  mutate(eos_palma_level = "se") %>% rename(palma_id = se_palma_id)

env_param<- system_joins %>%
  select(ep_palma_id) %>%
  distinct(ep_palma_id) %>%
  mutate(eos_palma_level = "ep") %>% rename(palma_id = ep_palma_id)

eos_palma <- do.call("rbind", list(ntwk, sys, plat, sensing_element, env_param))
```


```{r pressure, echo=FALSE}
vti_palma_notinEOS_nosiaII<- datasrc %>%
  filter(!data_source_palma_id %in% eos_palma$palma_id) %>%
  filter(data_source_type %in% c("ObsSys", "SvPrd_p")) %>%
  select(data_source_id:data_source_palma_id) %>%
  filter(value_tree_name == "NOSIA-II")
```


#NOSIA-2-1
```{r}
eores<-"https://eoreswstest2.nesdis-hq.noaa.gov/ws/ws/"

#treename<-"EOA2016"
#treename<-"NOSIA-II"
treename<-"NOSIA-2-1"
```

```{r}
#networks
r<-GET(paste0(eores,"get_reports_network_basic_information",sep=""))
json_text<-content(r, as = "text")
networks_json<-fromJSON(json_text)
networks<-networks_json[['rptntwrkbasic']]

#networks palma
r<-GET(paste0(eores,"get_reports_network_palma_id",sep=""))
json_text<-content(r, as = "text")
networks_palma_json<-fromJSON(json_text)
networks_palma<-networks_palma_json[['rptntwrkpalmaid']]

#networks2systems
r<-GET(paste0(eores,"get_reports_network_observing_system_associations",sep=""))
json_text<-content(r, as = "text")
networks2systems_json<-fromJSON(json_text)
networks2systems<-networks2systems_json[['rptntwrk2system']]

#systems
r<-GET(paste0(eores,"get_reports_observing_system_basic_information",sep=""))
json_text<-content(r, as = "text")
systems_json<-fromJSON(json_text)
systems<-systems_json[['rptsystembasic']]

#systems palma
r<-GET(paste0(eores,"get_reports_observing_system_palma_id",sep=""))
json_text<-content(r, as = "text")
systems_palma_json<-fromJSON(json_text)
systems_palma<-systems_palma_json[['rptsystempalmaid']]

#platforms
r<-GET(paste0(eores,"get_reports_platform_basic_information",sep=""))
json_text<-content(r, as = "text")
platforms_json<-fromJSON(json_text)
platforms<-platforms_json[['rptpltfrmbasic']]

#platform palma
r<-GET(paste0(eores,"get_reports_platform_palma_id",sep=""))
json_text<-content(r, as = "text")
platforms_palma_json<-fromJSON(json_text)
platforms_palma<-platforms_palma_json[['rptpltfrmpalmaid']]

#platforms2system
r<-GET(paste0(eores,"get_reports_observing_system_platform_associations",sep=""))
json_text<-content(r, as = "text")
platform2system_json<-fromJSON(json_text)
platform2system<-platform2system_json[['rptsystem2pltfrm']]

#Sensing Elements
r<-GET(paste0(eores,"get_reports_sensing_element_basic_information",sep=""))
json_text<-content(r, as = "text")
se_json<-fromJSON(json_text)
se<-se_json[['rptsebasic']]

#Sensing Elements palma
r<-GET(paste0(eores,"get_reports_sensing_element_palma_id",sep=""))
json_text<-content(r, as = "text")
se_palma_json<-fromJSON(json_text)
se_palma<-se_palma_json[['rptsepalmaid']]

#se2platform
r<-GET(paste0(eores,"get_reports_platform_sensing_element_associations",sep=""))
json_text<-content(r, as = "text")
se2platform_json<-fromJSON(json_text)
se2platform<-se2platform_json[['rptpltfrm2se']]

#environmental parameters
r<-GET(paste0(eores,"get_reports_environmental_parameter_basic_information",sep=""))
json_text<-content(r, as = "text")
ep_json<-fromJSON(json_text)
ep<-ep_json[['rptenvparambasic']]

#environmental parameters palma
r<-GET(paste0(eores,"get_reports_environmental_parameter_palma_id",sep=""))
json_text<-content(r, as = "text")
ep_palma_json<-fromJSON(json_text)
ep_palma<-ep_palma_json[['rptenvparampalmaid']]

#se2ep
r<-GET(paste0(eores,"get_reports_sensing_element_environmental_parameter_associations",sep=""))
json_text<-content(r, as = "text")
ep2se_json<-fromJSON(json_text)
ep2se<-ep2se_json[['rptse2envparam']]

#data sources
r<-GET(paste0(eores,"get_reports_data_sources",sep=""))
json_text<-content(r, as = "text")
datasrc_json<-fromJSON(json_text)
datasrc<-datasrc_json[['rptdatasrc']]
```

```{r}
system_joins <- networks_palma %>%
  left_join(networks, by = "network_id") %>% 
  select(network_id:network_acronym) %>% 
  left_join(networks2systems, by = "network_id") %>% 
  select(-network_id, -network_system_id) %>% 
  dplyr::rename(networks_palma_id = palma_id) %>%
  full_join(systems, by = "system_id")%>%
#  filter(osc_baseline_observing_system_category== "Critical") %>%
  select(network_name, network_acronym, networks_palma_id, system_id, system_name, system_acronym, system_life_cycle_phase, system_type) %>%
  left_join(systems_palma, by = "system_id") %>%
  left_join(platform2system, by = "system_id") %>% 
  select(-system_id, -system_palma_id_id, -system_platform_id) %>%
  left_join(platforms, by = "platform_id") %>% 
  select(network_name:platform_acronym, platform_life_cycle_phase) %>% 
  dplyr::rename(systems_palma_id = palma_id) %>% 
  left_join(platforms_palma, by = "platform_id") %>%
  left_join(se2platform, by = "platform_id") %>%
  select(-platform_id, -platform_palma_id_id, -platform_sensing_element_id) %>%
  dplyr::rename(platforms_palma_id = palma_id) %>%
  left_join(se, by = "sensing_element_id") %>% 
  select(network_name:sensing_element_acronym, sensing_element_life_cycle_phase) %>% 
  left_join(se_palma, by = "sensing_element_id") %>% 
  dplyr::rename(se_palma_id = palma_id) %>%
  left_join(ep2se, by = "sensing_element_id") %>% 
  select(-sensing_element_palma_id_id, -sensing_element_environmental_parameter_id) %>% 
  left_join(ep, by = "environmental_parameter_id") %>% 
  select(network_name:environmental_parameter_name) %>% 
  left_join(ep_palma, by = "environmental_parameter_id") %>% 
  select(-environmental_parameter_id, -environmental_parameter_palma_id_id, -sensing_element_id) %>%
  dplyr::rename(ep_palma_id = palma_id) %>%
  mutate(acro_palma_all = paste(network_acronym, networks_palma_id, system_acronym, systems_palma_id, platform_acronym, platforms_palma_id, sensing_element_acronym, se_palma_id, ep_palma_id, sep = ";")) %>%
  distinct(acro_palma_all, .keep_all = TRUE)
```

```{r cars}
ntwk<- system_joins %>%
  select(networks_palma_id) %>%
  distinct(networks_palma_id) %>%
  mutate(eos_palma_level = "network") %>% rename(palma_id = networks_palma_id)

sys<- system_joins %>%
  select(systems_palma_id) %>%
  distinct(systems_palma_id) %>%
  mutate(eos_palma_level = "system") %>% rename(palma_id = systems_palma_id)

plat<- system_joins %>%
  select(platforms_palma_id) %>%
  distinct(platforms_palma_id) %>%
  mutate(eos_palma_level = "platform") %>% rename(palma_id = platforms_palma_id)

sensing_element<- system_joins %>%
  select(se_palma_id) %>%
  distinct(se_palma_id) %>%
  mutate(eos_palma_level = "se") %>% rename(palma_id = se_palma_id)

env_param<- system_joins %>%
  select(ep_palma_id) %>%
  distinct(ep_palma_id) %>%
  mutate(eos_palma_level = "ep") %>% rename(palma_id = ep_palma_id)

eos_palma <- do.call("rbind", list(ntwk, sys, plat, sensing_element, env_param))
```

```{r}
vti_palma_notinEOS_nosia21<- datasrc %>%
  filter(!data_source_palma_id %in% eos_palma$palma_id) %>%
  filter(data_source_type %in% c("ObsSys", "SvPrd_p")) %>%
  select(data_source_id:data_source_palma_id) %>%
  filter(value_tree_name == "NOSIA-2-1")


vti_palma_matchEOS_nosiaII<- datasrc %>%
  filter(data_source_palma_id %in% eos_palma$palma_id) %>%
  left_join(eos_palma, by = c("data_source_palma_id" = "palma_id"))
```


```{r}
sheets<- list("NOSIA-II"= vti_palma_notinEOS_nosiaII, "NOSIA-2-1" = vti_palma_notinEOS_nosia21)
write_xlsx(sheets,"C:/Users/Elizabeth.Gugliotti/Documents/code/output/vti_palma_notin_EOS.xlsx")
```